# Generated by Django 3.1.7 on 2024-10-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20241009_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='400bb0', max_length=6),
        ),
    ]
