# Generated by Django 3.1.7 on 2024-09-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20240930_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtpToken',
        ),
    ]
