# Generated by Django 3.1.7 on 2024-09-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20240917_0838'),
        ('accounts', '0012_delete_onetimepassword'),
    ]

    operations = [
    ]
