# Generated by Django 3.1.7 on 2024-10-01 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_merge_20240920_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountActivateToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activate_token', models.UUIDField(default=uuid.uuid4)),
                ('expired_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activate_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
