# Generated by Django 3.1.7 on 2024-09-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_merge_20240920_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tournament_name',
            field=models.CharField(default='noob', max_length=100),
        ),
    ]
