# Generated by Django 3.1.7 on 2024-10-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20241001_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='0d70f0', max_length=6),
        ),
    ]
