# Generated by Django 3.1.7 on 2024-09-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20240926_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='noob.png', upload_to=''),
        ),
    ]
