# Generated by Django 3.1.7 on 2024-10-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20241004_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend_list',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='62f9e5', max_length=6),
        ),
    ]
