# Generated by Django 3.1.7 on 2024-10-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20241007_1603'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendshiprequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='sender',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='b01e7a', max_length=6),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.DeleteModel(
            name='FriendshipRequest',
        ),
    ]
