# Generated by Django 3.1.7 on 2024-10-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20241008_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='179b72', max_length=6),
        ),
    ]
