global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'transcendence.simplepong@gmail.com'
  smtp_auth_username: 'transcendence.simplepong@gmail.com'
  smtp_auth_password: 'feov cjkg mylj aise'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'otxoboy64@gmail.com'
        send_resolved: true

# receivers:
#   - name: 'email'
#     email_configs:
#       - to: 'otxoboy64@gmail.com'
#         from: 'transcendence.simplepong@gmail.com'
#         smarthost: 'smtp.gmail.com:587'
#         auth_username: 'transcendence.simplepong'
#         auth_password: 'feov cjkg mylj aise'
