  - name: instance-health
    rules:
      # CPU Usage Alert
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected on instance {{ $labels.instance }}"
          description: "CPU usage is above 80% for more than 2 minutes. Current value: {{ $value }}%"
      
      # Memory Usage Alert
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected on instance {{ $labels.instance }}"
          description: "Memory usage is above 85% for more than 2 minutes. Current value: {{ $value }}%"
      
      # Instance Down Alert
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} is down"
          description: "Prometheus has not scraped the instance {{ $labels.instance }} for more than 1 minute."

  - name: database-health
    rules:
      # Postgres Unavailable Alert
      - alert: PostgresDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Postgres is down on {{ $labels.instance }}"
          description: "Postgres is unreachable for more than 1 minute."
