global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'otxoboy64@gmail.com'
        from: 'transcendence.simplepong@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'transcendence.simplepong'
        auth_password: 'password0.'
